name: suno_flutter
description: Suno mobile app for YouTube to MP3 conversion

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  url_launcher: ^6.1.11
  flutter_dotenv: ^5.1.0
  path_provider: ^2.0.15
  permission_handler: ^10.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
